doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    server_version: '8.0'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App\Domain:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src'
        prefix: 'App\Domain'
        alias: App\Domain
