security:
  password_hashers:
    App\Domain\User:
      algorithm: auto
  enable_authenticator_manager: true
  providers:
    app_user_provider:
      entity:
        class: App\Domain\User
        property: email
  firewalls:
    login:
      pattern: ^/api/v1/login
      stateless: true
      json_login:
        check_path: /api/v1/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
    api:
      pattern: ^/api
      stateless: true
      jwt: ~
  access_control:
    - { path: ^/api/v1/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
