###############################################################################
#                          Generated on .docker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: eis-redis

    mysql:
      image: mysql:8.0
      container_name: eis-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=eis
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
      ports:
        - "8002:3306"

    webserver:
      image: nginx:alpine
      container_name: eis-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: .docker/php-fpm
      container_name: eis-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini

