parameters:
  invoice_file_upload_path: '/application/_upload_files'
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  App\Application\Handler\UploadInvoiceFileHandler:
    arguments:
      $uploadFilePath: '%invoice_file_upload_path%'

  App\Infrastructure\Filesystem\FileStorage:
    arguments:
      $invoiceFilesPath: '%invoice_file_upload_path%'
