parameters:
  invoice_file_upload_path: '/application/_upload_files'
  exception_to_code:
    App\Domain\Exception\DomainLogicException: 400
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  App\Application\Handler\UploadInvoiceFileHandler:
    arguments:
      $uploadFilePath: '%invoice_file_upload_path%'

  App\Infrastructure\Filesystem\FileStorage:
    arguments:
      $invoiceFilesPath: '%invoice_file_upload_path%'
  App\Infrastructure\Symfony\EventListener\GeneralApiExceptionListener:
    arguments:
      $returnCodeMap: '%exception_to_code%'
