parameters:
  invoice_file_upload_path: '/application/_upload_files'
  exception_to_code:
    App\Domain\Exception\DomainLogicException: 400
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  # APPLICATION

  App\Application\Handler\UploadInvoiceFileHandler:
    arguments:
      $uploadFilePath: '%invoice_file_upload_path%'

  # INFRASTRUCTURE

  app.infrastructure.file_storage:
    class: Symfony\Component\Finder\Finder
    calls:
      - in: [ '%invoice_file_upload_path%' ]

  App\Infrastructure\Filesystem\FileStorage:
    arguments:
      $finder: '@app.infrastructure.file_storage'
  App\Infrastructure\Symfony\EventListener\GeneralApiExceptionListener:
    arguments:
      $returnCodeMap: '%exception_to_code%'

